/gazebo_ros_control:
  pid_gains:
    finger_joint:
      finger_p: 20
      finger_i: 0.01
      finger_d: 0.0
      finger_velocity_p: 0.1
      finger_velocity_i: 0.01
      finger_velocity_d: 0.0

    right_outer_knuckle_joint:
      p: 10.0
      i: 0.01
      d: 0.05
